import 'package:flutter_test/flutter_test.dart';
import 'package:calories_app/domain/meal_plans/explore_meal_plan.dart';
import 'package:calories_app/domain/meal_plans/user_meal_plan.dart';
import 'package:calories_app/domain/meal_plans/meal_plan_goal_type.dart';
import 'package:calories_app/domain/profile/profile.dart';
import 'package:calories_app/features/meal_plans/domain/services/apply_explore_template_service.dart';

/// Regression test: Ensure applying an explore template clears old active plan
/// and sets exactly one new active plan
void main() {
  group('ApplyExploreTemplateService Active Plan Invariant', () {
    test('applying template creates active plan with correct fields', () {
      // Create a test template
      final template = ExploreMealPlan(
        id: 'template-123',
        name: 'Test Template',
        goalType: MealPlanGoalType.loseFat,
        description: 'Test description',
        templateKcal: 1500,
        durationDays: 7,
        mealsPerDay: 3,
        tags: ['healthy', 'low-cal'],
        isFeatured: false,
        isPublished: true,
        isEnabled: true,
        createdAt: DateTime(2024, 1, 1),
        updatedAt: DateTime(2024, 1, 2),
        createdBy: 'admin-123',
        difficulty: 'medium',
      );

      // Create a test profile
      final profile = Profile(
        nickname: 'Test User',
        gender: 'male',
        heightCm: 175,
        weightKg: 75.0,
        activityLevel: 'moderate',
        goalType: 'lose_weight',
        targetKcal: 1500.0,
        targetWeight: 70.0,
        weeklyDeltaKg: -0.5,
        createdAt: DateTime(2024, 1, 1),
      );

      // Apply template
      final userPlan = ApplyExploreTemplateService.applyTemplate(
        template: template,
        userId: 'user-123',
        profile: profile,
        setAsActive: true,
      );

      // Verify the plan is active
      expect(userPlan.isActive, isTrue, reason: 'Applied plan must be active');
      
      // Verify all required fields are copied
      expect(userPlan.name, equals(template.name));
      expect(userPlan.goalType, equals(template.goalType));
      expect(userPlan.durationDays, equals(template.durationDays));
      expect(userPlan.dailyCalories, equals(1500)); // Uses profile.targetKcal
      expect(userPlan.type, equals(UserMealPlanType.template));
      expect(userPlan.status, equals(UserMealPlanStatus.active));
      expect(userPlan.planTemplateId, equals(template.id));
      expect(userPlan.userId, equals('user-123'));
      
      // Verify plan has valid ID (will be generated by repository, but should not be empty)
      expect(userPlan.id, isEmpty, reason: 'ID will be generated by repository');
    });

    test('applying template uses template kcal when profile targetKcal is null', () {
      final template = ExploreMealPlan(
        id: 'template-123',
        name: 'Test Template',
        goalType: MealPlanGoalType.maintain,
        description: 'Test description',
        templateKcal: 2000,
        durationDays: 7,
        mealsPerDay: 3,
        tags: [],
        isFeatured: false,
        isPublished: true,
        isEnabled: true,
        createdAt: DateTime(2024, 1, 1),
        difficulty: null,
      );

      final profile = Profile(
        nickname: 'Test User',
        gender: 'male',
        heightCm: 175,
        weightKg: 75.0,
        activityLevel: 'moderate',
        goalType: 'maintain_weight',
        targetKcal: null, // No target kcal
        targetWeight: 75.0,
        weeklyDeltaKg: 0.0,
        createdAt: DateTime(2024, 1, 1),
      );

      final userPlan = ApplyExploreTemplateService.applyTemplate(
        template: template,
        userId: 'user-123',
        profile: profile,
        setAsActive: true,
      );

      // Should use template kcal when profile targetKcal is null
      expect(userPlan.dailyCalories, equals(2000));
    });

    test('applying template with setAsActive=false creates inactive plan', () {
      final template = ExploreMealPlan(
        id: 'template-123',
        name: 'Test Template',
        goalType: MealPlanGoalType.maintain,
        description: 'Test description',
        templateKcal: 2000,
        durationDays: 7,
        mealsPerDay: 3,
        tags: [],
        isFeatured: false,
        isPublished: true,
        isEnabled: true,
        createdAt: DateTime(2024, 1, 1),
      );

      final profile = Profile(
        nickname: 'Test User',
        gender: 'male',
        heightCm: 175,
        weightKg: 75.0,
        activityLevel: 'moderate',
        goalType: 'maintain_weight',
        targetKcal: 2000.0,
        targetWeight: 75.0,
        weeklyDeltaKg: 0.0,
        createdAt: DateTime(2024, 1, 1),
      );

      final userPlan = ApplyExploreTemplateService.applyTemplate(
        template: template,
        userId: 'user-123',
        profile: profile,
        setAsActive: false, // Explicitly set to inactive
      );

      // Should respect setAsActive parameter
      expect(userPlan.isActive, isFalse);
      expect(userPlan.status, equals(UserMealPlanStatus.active)); // Status is still active, but isActive flag is false
    });
  });
}

