import 'package:flutter/foundation.dart';
import 'package:calories_app/domain/meal_plans/explore_meal_plan.dart';
import 'package:calories_app/domain/meal_plans/user_meal_plan.dart' show UserMealPlan, UserMealPlanType, UserMealPlanStatus;
import 'package:calories_app/features/meal_plans/domain/services/kcal_calculator.dart';
import 'package:calories_app/domain/profile/profile.dart';

/// Pure domain service for applying explore templates to user plans
/// 
/// This service handles the business logic of converting a generic explore template
/// into a personalized user meal plan, adjusting kcal based on user profile.
/// 
/// No Flutter or Firestore dependencies.
class ApplyExploreTemplateService {
  /// Apply an explore template to create a user meal plan
  /// 
  /// Personalizes the template by:
  /// - Using user's targetKcal instead of template's generic kcal
  /// - Setting startDate to now
  /// - Marking as active if requested
  /// 
  /// Returns a UserMealPlan ready to be saved
  static UserMealPlan applyTemplate({
    required ExploreMealPlan template,
    required String userId,
    required Profile profile,
    bool setAsActive = true,
    DateTime? startDate,
  }) {
    // Determine personalized daily calories
    // Use user's targetKcal if available, otherwise use template's kcal
    final personalizedKcal = profile.targetKcal?.toInt() ?? template.templateKcal;

    // Ensure kcal is valid for the goal type
    final goalType = template.goalType;
    final isValidKcal = KcalCalculator.isValidCalorieForGoal(
      profile,
      goalType,
      personalizedKcal,
    );

    // If invalid, fall back to template kcal or a safe default
    final finalKcal = isValidKcal
        ? personalizedKcal
        : (template.templateKcal > 0 ? template.templateKcal : 2000);

    // Log metadata copy for verification
    debugPrint('[ApplyExplore] 🧾 template meta: desc="${template.description}", tags=${template.tags}, difficulty=${template.difficulty}');
    
    final userPlan = UserMealPlan(
      id: '', // Will be generated by repository
      userId: userId,
      planTemplateId: template.id,
      name: template.name,
      goalType: goalType,
      type: UserMealPlanType.template,
      startDate: startDate ?? DateTime.now(),
      currentDayIndex: 1,
      status: UserMealPlanStatus.active,
      dailyCalories: finalKcal,
      durationDays: template.durationDays,
      isActive: setAsActive,
      createdAt: DateTime.now(),
      // Copy metadata fields from template
      description: template.description,
      tags: template.tags,
      difficulty: template.difficulty,
    );
    
    debugPrint('[ApplyExplore] 🧾 userPlan meta: desc="${userPlan.description}", tags=${userPlan.tags}, difficulty=${userPlan.difficulty}');
    
    return userPlan;
  }
}

